### ISSUE TITLE
DelayedArray:::is_pristine() no longer available

### ISSUE THREAD

**Issue by PeteHaitch** [PeteHaitch/DelayedMatrixStats#45]
https://github.com/Bioconductor/DelayedArray/commit/6a3febf165f15101036a7adf6fb9a4830bda35f2#diff-976794b77d68c09b9ddcab5b7172f4fbR280

**Comment by LTLA** [comment]
Yes, I was going to mention this as well - a few parts of _scran_ are crashing as a result.

**Comment by PeteHaitch** [comment]
What I get for relying on unexported functions. Do you know if there's a replacement?

**Comment by LTLA** [comment]
Not that I know of - let's ask @hpages.

**Comment by hpages** [comment]
I recently commented out `is_pristine`, sorry.

It was used for example in the validity method for HDF5Array objects but now checking that the seed is an HDF5ArraySeed object is enough. The reason is that, starting with DelayedArray 0.5.24, the DelayedArray class only has one slot left: the `seed` slot. As soon as you start operating on the object the seed gets replaced with a DelayedOp object. So if the `seed` slot is not a DelayedOp object, then the object is pristine.

In DelayedArray >= 0.5.24 I modified `is_pristine` to be:
```
is_pristine <- function(x) { !is(x@seed, "DelayedOp") }
```
but I also commented it out. I just uncommented it (d54116704725e7b5017e6ab5e64021248ec4c248). 

Maybe I should export this? (and rename it `isPristine`)

**Comment by LTLA** [comment]
Thanks Herve. In the future, there may be some opportunity for consolidating `is_pristine()` with the functions proposed in Bioconductor/DelayedArray#5, as they all answer questions related to "what are the delayed operations?" for use in dependent APIs.

**Comment by PeteHaitch** [comment]
Thanks, Hervé.
